# vim: fileencoding=utf-8 foldmethod=marker

font_family      Fira Code
font_size 13.0
macos_thicken_font 0.1

disable_ligatures never

cursor_shape block
cursor_blink_interval 0

hide_window_decorations no
window_padding_width 4

editor vim

macos_option_as_alt both

include dracula.conf

scrollback_lines 20000

map cmd+shift+t new_tab_with_cwd

# BEGIN_KITTY_THEME
# 1984 Dark
include current-theme.conf
# END_KITTY_THEME

# font_family FiraCode

symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d4,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f532,U+f0001-U+f1af0 Symbols Nerd Font Mono

# Map F1 to broadcast input to all kitty windows
map f1 launch --allow-remote-control kitty +kitten broadcast

#tab_title_template        "{fmt.bg.default}{fmt.fg.white}{fmt.bg._61AFEF}{(f'{index} {title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 13 else f'{index} {title}').center(13, ' ')}{fmt.fg._61AFEF}{fmt.bg.default}{fmt.fg.default}{fmt.bg.default}"
#active_tab_title_template "{fmt.bg.default}{fmt.fg.white}{fmt.bg._98C379}{(f'{index} {title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 13 else f'{index} {title}').center(13, ' ')}{fmt.fg._98C379}{fmt.bg.default}{fmt.fg.default}{fmt.bg.default}"


#tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{fmt.bg._7cd5f1 + 'shepherd' + fmt.bg.tab if title == '~/env/home/dremio/projects/shepherd' else fmt.bg._baa0f8 + 'automation' + fmt.bg.tab if title == '~/env/home/dremio/projects/automation' else fmt.bg._ffb270 + 'macmon' + fmt.bg.tab if title == 'macmon' else title if tab.active_exe == '-zsh' else tab.active_exe}"

tab_bar_margin_width      9
tab_bar_margin_height     9 0
tab_bar_style             separator
tab_bar_min_tabs          1
tab_separator             ""
tab_title_template        "{fmt.fg._323449}{fmt.bg.default}{fmt.fg._04d1f9}{fmt.bg.default}{index}{fmt.fg._04d1f9}{fmt.bg._323449} {title[:15] + (title[15:] and '…')} {fmt.fg._323449}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._37f499}{fmt.bg.default}{fmt.fg._212337}{fmt.bg._37f499}{fmt.fg._212337}{fmt.bg._37f499} {title[:40] + (title[40:] and '…')} {fmt.fg._37f499}{fmt.bg.default} "
