# vim: fileencoding=utf-8 foldmethod=marker

font_family      Fira Code
font_size 13.0
macos_thicken_font 0.1

disable_ligatures never

cursor_shape block
cursor_blink_interval 0

hide_window_decorations no
window_padding_width 4

editor vim

macos_option_as_alt both

include dracula.conf

scrollback_lines 20000

map cmd+shift+t new_tab_with_cwd

# BEGIN_KITTY_THEME
# Monokai Pro
include current-theme.conf
# END_KITTY_THEME

# font_family FiraCode

symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d4,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f532,U+f0001-U+f1af0 Symbols Nerd Font Mono

# Map F1 to broadcast input to all kitty windows
map f1 launch --allow-remote-control kitty +kitten broadcast

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{fmt.bg._7cd5f1 + 'shepherd' + fmt.bg.tab if title == '~/env/home/dremio/projects/shepherd' else fmt.bg._baa0f8 + 'automation' + fmt.bg.tab if title == '~/env/home/dremio/projects/automation' else fmt.bg._ffb270 + 'macmon' + fmt.bg.tab if title == 'macmon' else title if tab.active_exe == '-zsh' else tab.active_exe}"
tab_bar_style powerline
tab_bar_min_tabs 1
tab_powerline_style slanted
