#!/usr/bin/env bash
# vim: foldmethod=marker

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# {{{ Disable Homebrew and APT confirmations for batch installs
export HOMEBREW_NO_ASK=1
export HOMEBREW_NO_REQUIRE_TAP_TRUST=1
export DEBIAN_FRONTEND=noninteractive
# }}}

# {{{ Dotbot requires git and Python 3.x
sudo apt update --yes
sudo apt install --yes \
  git \
  python3
# }}}

# {{{ Init submodules as some are required dotbot plugins
git -C "${BASEDIR}" submodule update --init --recursive
# }}}

# {{{ Delegate the rest to dotbot but exclude asdf at is is not yet installed
"${BASEDIR}/install" --except asdf
# }}}

# {{{ Now invoke dotbot again only for asdf in a new shell to reload the path
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
zsh -c "'${BASEDIR}/install' --only asdf"
# }}}

# {{{ Set shell to zsh
sudo usermod -s /usr/bin/zsh $(id --user --name)
# }}}
