#!/usr/bin/env bash
# vim: foldmethod=marker

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# {{{ First, we call dotbot to setup subodules, omz and install dotfiles
"${BASEDIR}/install" install.conf.yaml
# }}}

# {{{ Then we linuxify this mac but we reject changing the terminal to latest bash
pushd "${BASEDIR}/linuxify"
./linuxify install <<<"N"
popd
# }}}

# {{{ Change OSX settings, although not sure whether this still does much
# Stolen form https://github.com/skwp/dotfiles/blob/master/osx

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Enable subpixel font rendering on non-Apple LCDs
defaults write NSGlobalDomain AppleFontSmoothing -int 2

# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 0

# Show status bar in Finder
defaults write com.apple.finder ShowStatusBar -bool true

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Enable snap-to-grid for desktop icons
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# Kill affected applications
for app in Finder Dock Mail Safari iTunes iCal Address\ Book SystemUIServer; do killall "$app" >/dev/null 2>&1; done
echo "OSX Hacks Done. Note that some of these changes require a logout/restart to take effect."
# }}}

# {{{ Install Homebrew packages
brew install --yes \
  asdf \
  autoenv \
  autojump \
  bat \
  btop \
  coreutils \
  csshx \
  duti \
  dyff \
  fd \
  fswatch \
  fzf \
  gh \
  git-delta \
  gnuplot \
  grepai \
  helm \
  htop \
  jmeter \
  jq \
  k9s \
  kubectx \
  kubernetes-cli \
  lazygit \
  macmon \
  nvim \
  pandoc \
  parallel \
  pipx \
  ripgrep \
  the_silver_searcher \
  tmux \
  tree \
  tree-sitter \
  tree-sitter-cli \
  universal-ctags \
  wget
# }}}

# {{{ Install Homebrew Casks applications
brew trust --formula yoanbernabeu/tap/grepai

brew install --cask \
  font-fira-code \
  font-jetbrains-mono \
  font-symbols-only-nerd-font \
  gitx \
  kitty
# }}}
