#!/bin/bash

if [ -z "$1" ]
then
    echo "Usage: $0 <path-to-submodule>" >&2
    exit 1
fi

set -x

# From: https://gist.github.com/myusuf3/7f645819ded92bda6677

# Delete the relevant section from the .gitmodules file
gsed -i -e "/\[submodule \".*$1\"\]/,+2d" .gitmodules

# Stage the .gitmodules changes
git add .gitmodules

# Delete the relevant section from .git/config.
gsed -i -e "/\[submodule \".*$1\"\]/,+1d" .git/config

# Run git rm --cached path_to_submodule
git rm --cached vim/bundle/$1

# Run rm -rf .git/modules/path_to_submodule (no trailing slash).
rm -rf .git/modules/vim/bundle/$1

# Commit
git commit -m "Remove submodule $1"

# Delete the now untracked submodule files
rm -rf vim/bundle/$1

