#!/bin/bash

pushd ~

ln -sf ~/dotfiles/.grc/ ~/.grc
ln -sf ~/dotfiles/global-gitignore ~/.gitignore
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/zpreztorc ~/.zpreztorc
ln -sf ~/dotfiles/screenrc ~/.screenrc
mkdir -p ~/.config/nvim
ln -sf ~/dotfiles/init.vim ~/.config/nvim/init.vim

popd
