#!/bin/bash

pushd ~

ln -sf ~/dotfiles/.grc/ ~/.grc
ln -sf ~/dotfiles/global-gitignore ~/.gitignore
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/screenrc ~/.screenrc
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/vim ~/.vim
pushd dotfiles
git submodule init
git submodule update
popd

popd

